### ISSUE TITLE
submissions json data error

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#78]
http://omkserver.com/omk/odk/submissions/gn_buildings.json
returns
```
{"status":500,"msg":"Problem reading data.json file in submission directory. dataFile: /opt/omk/OpenMapKitServer/data/submissions/gn_buildings/35659135-894b-45db-98ec-3dfecefe1949/data.json","err":{"errno":-24,"code":"EMFILE","syscall":"open","path":"/opt/omk/OpenMapKitServer/data/submissions/gn_buildings/35659135-894b-45db-98ec-3dfecefe1949/data.json"}}
```

**Comment by ahmedOpeyemi** [comment]
@danbjoseph Any fix for this yet or any work being done on this? Currently having this issue on a locally deployed instance.
From what i have seen so far, using graceful-fs (https://github.com/isaacs/node-graceful-fs) to access filesystem works better than using nodes default fs module.

**Comment by hallahan** [comment]
@ahmedOpeyemi - has this been resolved?

**Comment by ahmedOpeyemi** [comment]
@hallahan this was fixed in https://github.com/AmericanRedCross/OpenMapKitServer/issues/85
@danbjoseph can test the http://omkserver.com/omk/odk/submissions/gn_buildings.json endpoint from his end to confirm & close the issue.

**Comment by danbjoseph** [comment]
I don't think the code has been deployed to the server yet. Still receiving the error message.

**Comment by hallahan** [comment]
@danbjoseph - Can you check the latest version? I think this was resolved.

**Comment by danbjoseph** [comment]
http://omkserver.com/omk/odk/submissions/gn_buildings.json
returns a 502 nginx bad gateway
and http://omkserver.com/omk/pages/submissions/?form=gn_buildings doesn't show anything
